### ISSUE TITLE
Will this repo help with grounding GPT-Neo results?

### ISSUE THREAD

**Issue by priya-dwivedi** [LouisCastricato/GPT-Neo-visual-grounding#35]
We are working on a problem to understand if generated results from GPT-Neo/GPT2 are grounded. By grounded I mean, it is pulling statistics and common sense knowledge from the underlying database and not hallucinating them. Is this repo to check if GPT-Neo is generating grounded outputs?

**Comment by LouisCastricato** [comment]
No, we know it is not generating grounded outputs. This is to improve that. It’s been difficult thus far but we’re getting there.

**Comment by priya-dwivedi** [comment]
Thanks!
